parameters:
#    rapp_page.example.class: Rapp\PageBundle\Example

services:
#    rapp_page.example:
#        class: %rapp_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
